Refactor Integration Test
CleytonJDSouza/vetdata pull request #17
Opened 2024-11-06 16:15 UTC by CleytonJDSouza

# Refactor Integration Test

## Type
- [ ] Hotfix
- [ ] New feature
- [x] Refactor / Improvements

## Context
- Refatoração na entidade DogBreed onde retirei todas as validações e de campos obrigatórios (@Notnull, @NotBlank) e deixei somente no DogBreedCreateDTO.
- Refatorei a classe ErrorHandler para que tratar melhor as exceções.
- Criado os testes integrados da classe DogBreedServiceImplIT.

### Coverage Tests
![1](https://github.com/user-attachments/assets/7320cbc7-ce25-4faf-ac90-f9b6d428be0d)

### Checklist
- [x] Criar testes integrados da classe DogBreedServiceImplIT.
- [x] Cobrir 80% do código por testes.

2024-12-16 23:53 UTC, santaniello requested changes

2024-12-16 23:53 UTC, santaniello commented on src/main/java/com/project/vetdata/service/DogBreedExternalService.java
> +        } catch (HttpClientErrorException e) {
Eu acredito que independente da exceção que rolar, a gente poderia retornar um ExternalApiException pois não temos nenhuma tratativa para o erro.

Algo mais ou menos assim:

```java
try {
       
}catch(Exception ex){
   throw new ExternalAPIException("Error to call Dog API: ", ex.getMessage());

}
```

2025-01-06 20:51 UTC, CleytonJDSouza commented on src/main/java/com/project/vetdata/service/DogBreedExternalService.java
> +        } catch (HttpClientErrorException e) {
Atualizei conforme o sugerido, funcionou corretamente.

2025-01-07 23:19 UTC, santaniello approved these changes

2025-01-07 23:19 UTC, santaniello commented on src/main/java/com/project/vetdata/service/DogBreedExternalService.java
> +        } catch (HttpClientErrorException e) {
Boaaaa

2025-01-07 23:19 UTC, merged